apiVersion: apps/v1
kind: Deployment
metadata:
  name: "currency-deployment"
  labels:
    app: currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: currency
        image: bazaar-currency  # Placeholder for bazaar-payment or bazaar-gst
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"    # Keeping it tiny for your 8GB RAM
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10