apiVersion: apps/v1
kind: Deployment
metadata:
  name: "email-deployment"
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: bazaar-email  # Placeholder for bazaar-payment or bazaar-gst
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"    # Keeping it tiny for your 8GB RAM
            cpu: "100m"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10