apiVersion: v1
kind: Service
metadata:
  name: "finance-service"
spec:
  type: NodePort
  selector:
    app: finance
  ports:
    - protocol: TCP
      port: 80         # Internal port
      targetPort: 3000 # The port your Node app listens on